import { GetServerSideProps, InferGetServerSidePropsType } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import SqliteVideoDb, { Video } from '../lib/db'
import Link from 'next/link'
import VideoPlayer from '../components/VideoPlayer'

export const getServerSideProps: GetServerSideProps<{ videos: Video[] }> = async (ctx) => {
  const videos = await SqliteVideoDb.getAllVideos()
  return {
    props: { videos }
  }
}

function Home({ videos }: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Multi Quality Video Player</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {videos.length === 0 ? (
          <div className={styles.title} >
            <h1>No Video</h1>
            <Link href="/upload">Upload a video</Link>
          </div>
        ) : (
          <VideoPlayer video={videos[0]} />
        )
        }
      </main >
    </div >
  )
}

export default Home
